version: '3'
services:
    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./certbot/www/:/var/www/certbot/:rw
            - ./certbot/conf/:/etc/letsencrypt/:rw
    mariadb:
        image: mariadb:latest
        restart: always
        env_file: ./mariadb/mariadb.env
        ports:
            - '3306:3306'
        volumes:
            - ./mariadb/fribblequibble_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
            - databasedata:/var/lib/mysql:rw
    api:
        build:
            context: .
            dockerfile: api.Dockerfile
        restart: always
        ports:
            - '8080:8080'
        depends_on:
            - mariadb
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        depends_on:
            - api

volumes:
    databasedata: {}
