version: '3'
services:
    mariadb:
        image: mariadb:latest
        restart: always
        env_file: ./mariadb/mariadb.env
        ports:
            - '127.0.0.1:3306:3306'
        volumes:
            - ./mariadb/fribblequibble_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
            - databasedata:/var/lib/mysql:rw
    api:
        build:
            context: .
            dockerfile: ./api/api.Dockerfile
        restart: always
        env_file:
            - ./api/api.env
        ports:
            - '127.0.0.1:8080:8080'
        volumes:
            - ./api/:/api/src/
        depends_on:
            - mariadb
        entrypoint: ["node", "/api/src/server.js"]
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf:ro
            - /usr/share/nginx/html/:/usr/share/nginx/html/:rw
            - /etc/letsencrypt/:/etc/nginx/ssl/:ro
        depends_on:
            - api

volumes:
    databasedata: {}
