version: '3'
services:
    mariadb:
        image: mariadb:latest
        restart: always
        env_file: ./mariadb/mariadb.env
        ports:
            - '3306:3306'
        volumes:
            - ./mariadb/fribblequibble_db.sql:/docker-entrypoint-initdb.d/init.sql
            - databasedata:/var/lib/mysql
    api:
        build:
            context: .
            dockerfile: api.Dockerfile
        restart: always
        ports:
            - '8080:8080'
        depends_on:
            - mariadb
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - api

volumes:
    databasedata: {}