version: '3'
services:
    mariadb:
        image: mariadb:latest
        restart: always
        env_file: ./mariadb/mariadb.env
        ports:
            - '127.0.0.1:3306:3306'
        volumes:
            - ./mariadb/fribblequibble_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
            - databasedata:/var/lib/mysql:rw
    api:
        build:
            context: .
            dockerfile: api.Dockerfile
        restart: always
        env_file:
            - ./api/api.env
            - ./api/api-dev.env
        ports:
            - '127.0.0.1:8080:8080'
        depends_on:
            - mariadb
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - api

volumes:
    databasedata: {}
